# Generated by Django 4.2.27 on 2026-01-28 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Item ka title dein', max_length=200)),
                ('description', models.TextField(help_text='Item ki mukammal description likhein')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents & ID Cards'), ('accessories', 'Accessories'), ('clothing', 'Clothing'), ('books', 'Books & Stationery'), ('keys', 'Keys'), ('wallet', 'Wallet & Money'), ('bags', 'Bags & Luggage'), ('other', 'Other')], default='other', help_text='Item ki category select karein', max_length=50)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', help_text='Item lost hai ya found', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Item ki tasveer upload karein (optional)', null=True, upload_to='item_images/')),
                ('location', models.CharField(help_text='Jahan item mili ya gumi - wo jagah likhein', max_length=255)),
                ('date_lost_found', models.DateField(help_text='Jis din item gumi ya mili')),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin ne verify kiya hai ya nahi')),
                ('is_resolved', models.BooleanField(default=False, help_text='Item claim ho gayi ya nahi')),
                ('posted_by', models.ForeignKey(help_text='Jis user ne item post ki', on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
